### ISSUE TITLE
ModuleNotFoundError: No module named 'playwright._impl._api_types'

### ISSUE THREAD

**Issue by sosojustdo** [bellingcat/tiktok-hashtag-analysis#25]
playwright-python version:1.40.0
Execute command line:tiktok-hashtag-analysis  -h

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.10.0/bin/tiktok-hashtag-analysis", line 5, in <module>
    from tiktok_hashtag_analysis.cli import main
  File "/usr/local/var/pyenv/versions/3.10.0/lib/python3.10/site-packages/tiktok_hashtag_analysis/__init__.py", line 1, in <module>
    from .base import TikTokDownloader
  File "/usr/local/var/pyenv/versions/3.10.0/lib/python3.10/site-packages/tiktok_hashtag_analysis/base.py", line 26, in <module>
    from playwright._impl._api_types import Error
ModuleNotFoundError: No module named 'playwright._impl._api_types'

<img width="1032" alt="image" src="https://github.com/bellingcat/tiktok-hashtag-analysis/assets/3364336/9df09e2b-49ff-46fd-9c0b-8058c103d9e0">

**Comment by bilkobe** [comment]
Same here, running on MacOS

```
  File "/opt/homebrew/lib/python3.11/site-packages/tiktok_hashtag_analysis/base.py", line 26, in <module>
    from playwright._impl._api_types import Error
ModuleNotFoundError: No module named 'playwright._impl._api_types'
```

**Comment by bilkobe** [comment]
Due to [comment here](https://github.com/Xewdy444/CF-Clearance-Scraper/issues/42), I downgraded Playwright to v1.39.0. It worked.
```
pip3 uninstall playwright
pip3 install playwright==1.39.0
playwright install
```

**Comment by sosojustdo** [comment]
@bilkobe Thank you support, The following used playwright version 1.39.0 worked, have a  nice day.
