### ISSUE TITLE
tiktok-hashtag-analysis search fails

### ISSUE THREAD

**Issue by jbfink** [bellingcat/tiktok-hashtag-analysis#38]
Hey folks,

Trying to do a simple search using this package, as `tiktok-hashtag-analysis london`, yields the following error output, along with a Playwright chrome window opening up and closing three times (with the url https://tiktok.com/explore).

Can someone verify that this package still works as expected? If I'm missing something very obvious, I apologize.

---

2024-11-26 16:32:38 INFO | Hashtags to scrape: ['london']
2024-11-26 16:32:38 INFO | Writing data to directory: /home/jbfink/tiktok_hashtag_data
2024-11-26 16:32:51 WARNING | Encountered error RetryError[<Future at 0x7925d6b3ddf0 state=finished ra
ised Error>] when fetching data, retrying in headed mode
Traceback (most recent call last):
  File "/home/jbfink/.local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in _
_call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/tiktok_hashtag_analysis/base.py", line 61, in
 _fetch_hashtag_data
    await api.create_sessions(
  File "/home/jbfink/.local/lib/python3.12/site-packages/TikTokApi/tiktok.py", line 264, in create_ses
sions
    await asyncio.gather(
  File "/home/jbfink/.local/lib/python3.12/site-packages/TikTokApi/tiktok.py", line 201, in __create_s
ession
    await self.__set_session_params(session)
  File "/home/jbfink/.local/lib/python3.12/site-packages/TikTokApi/tiktok.py", line 94, in __set_sessi
on_params
    user_agent = await session.page.evaluate("() => navigator.userAgent")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/playwright/async_api/_generated.py", line 849
5, in evaluate
    await self._impl_obj.evaluate(
  File "/home/jbfink/.local/lib/python3.12/site-packages/playwright/_impl/_page.py", line 467, in eval
uate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 278, in eva
luate
    await self._channel.send(
  File "/home/jbfink/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 61, in
 send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 528, i
n wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.evaluate: ReferenceError: opts is not defined
    at Navigator.get [as userAgent] (<anonymous>:11:42)
at eval (eval at evaluate (:234:30), <anonymous>:1:17)
    at UtilityScript.evaluate (<anonymous>:241:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jbfink/.local/bin/tiktok-hashtag-analysis", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/tiktok_hashtag_analysis/cli.py", line 147, in main
    downloader.run(
  File "/home/jbfink/.local/lib/python3.12/site-packages/tiktok_hashtag_analysis/base.py", line 336, in run
    self.get_hashtag_posts(hashtag=hashtag, limit=limit, headed=headed)
  File "/home/jbfink/.local/lib/python3.12/site-packages/tiktok_hashtag_analysis/base.py", line 189, in get_hashtag_posts
    fetched_data = asyncio.run(
                   ^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jbfink/.local/lib/python3.12/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbfink/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7925d685c680 state=finished raised Error>]

**Comment by ftk789** [comment]
same. seems like an issue for everyone if I'm not wrong.
